### ISSUE TITLE
Format : saut de page entre chaque hymne

### ISSUE THREAD

**Issue by FrSimonMarie** [xmarteo/hymnarium_op#1]
Le format de recueil proposé est bon.
A court terme, nous imprimerons chaque hymne **sur une feuille séparée** : nous utilisons un classeur artisanal dans lequel nous ajoutons petit à petit tout ce qui est insuffisant dans l'antiphonaire (partition manquante, psaumes non marquées, offices plus récents ou locaux, etc.).
A long terme, ce classeur ne suffira plus et il faudra quelque chose de plus propre mais nous allons probablement continuer encore longtemps avec celui-ci.

Est-il possible de mettre un saut de page entre chaque hymne?

**Comment by xmarteo** [comment]
"Le format de recueil proposé est bon" => on conserve le format de page ? Si on imprime sur A4 cela rendra grand, mais c'est un effet qu'on peut vouloir rechercher.

**Comment by xmarteo** [comment]
Bien prendre en compte https://github.com/xmarteo/hymnarium_op/blob/main/hymnarium_op_loose.pdf 
Je laisse l'autre fichier car il servira de base à une éventuelle extension du projet
