### ISSUE TITLE
Strophes Christe sanctorum decus angelorum

### ISSUE THREAD

**Issue by xmarteo** [xmarteo/hymnarium_op#8]
Gillet fait figurer sans rubrique particulière les trois strophes des trois archanges (Angelum pacis, Angelum fortis, Angelus nobis medicum). Vérifier dans un bréviaire OP si une seule est dite à chacune des trois fêtes, ou si les trois sont toujours dites.

**Comment by FrSimonMarie** [comment]
Les trois strophes sont dites à la saint Michel (ce n'est pas le cas pour la saint Raphaël, où l'on ne garde que sa strophe. Saint Gabriel est fêté pendant le carême. On prend donc l'hymne du temps).
