### ISSUE TITLE
Doxologie pour Cor arca legem continens (Sacré-Cœur)

### ISSUE THREAD

**Issue by xmarteo** [xmarteo/hymnarium_op#9]
Le supplément au Gillet donne "Gloria", points de suspension. Je ne trouve pas de doxologie qui soit évidemment la bonne (Qui natus es, Qui surrexisti, Qui apparuisti... ?)

Quelle est la bonne ?

**Comment by xmarteo** [comment]
(DivinumOfficium.com, dont je me sers en l'absence d'un scan de bréviaire OP post 1948, a la doxologie Jesu tibi, comme au Romain, mais c'est peut-être erroné)

**Comment by FrSimonMarie** [comment]
Voici la doxologie que donne le bréviaire OP de 1962, tome 2, p. 64, (difficile de la deviner !) :
Glória tibi, Dómine,
Qui Corde fundis grátiam,
Cum Patre et Sancto Spíritu
In sempitérna saécula. Amen

J'ai remarqué que DivinumOfficium est généralement fautif pour les doxologies op.

**Comment by xmarteo** [comment]
Fixed in [8bb3d20](https://github.com/xmarteo/hymnarium_op/commit/8bb3d20181b51666199aabf0724a15969cae1beb)
